package com.aaron.resource.website.mapper;

import com.aaron.resource.website.pojo.TbWxAccount;
import com.aaron.resource.website.pojo.TbWxAccountExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TbWxAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wx_account
     *
     * @mbggenerated
     */
    int countByExample(TbWxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wx_account
     *
     * @mbggenerated
     */
    int deleteByExample(TbWxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wx_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wx_account
     *
     * @mbggenerated
     */
    int insert(TbWxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wx_account
     *
     * @mbggenerated
     */
    int insertSelective(TbWxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wx_account
     *
     * @mbggenerated
     */
    List<TbWxAccount> selectByExample(TbWxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wx_account
     *
     * @mbggenerated
     */
    TbWxAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wx_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbWxAccount record, @Param("example") TbWxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wx_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbWxAccount record, @Param("example") TbWxAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wx_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbWxAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wx_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbWxAccount record);
}