package com.aaron.resource.website.pojo;

public class TbWxAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_account.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_account.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_account.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_account.avatarUrl
     *
     * @mbggenerated
     */
    private String avatarurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_account.gender
     *
     * @mbggenerated
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_account.nickName
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_account.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_account.language
     *
     * @mbggenerated
     */
    private String language;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_account.id
     *
     * @return the value of tb_wx_account.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wx_account.id
     *
     * @param id the value for tb_wx_account.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_account.province
     *
     * @return the value of tb_wx_account.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wx_account.province
     *
     * @param province the value for tb_wx_account.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_account.city
     *
     * @return the value of tb_wx_account.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wx_account.city
     *
     * @param city the value for tb_wx_account.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_account.avatarUrl
     *
     * @return the value of tb_wx_account.avatarUrl
     *
     * @mbggenerated
     */
    public String getAvatarurl() {
        return avatarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wx_account.avatarUrl
     *
     * @param avatarurl the value for tb_wx_account.avatarUrl
     *
     * @mbggenerated
     */
    public void setAvatarurl(String avatarurl) {
        this.avatarurl = avatarurl == null ? null : avatarurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_account.gender
     *
     * @return the value of tb_wx_account.gender
     *
     * @mbggenerated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wx_account.gender
     *
     * @param gender the value for tb_wx_account.gender
     *
     * @mbggenerated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_account.nickName
     *
     * @return the value of tb_wx_account.nickName
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wx_account.nickName
     *
     * @param nickname the value for tb_wx_account.nickName
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_account.country
     *
     * @return the value of tb_wx_account.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wx_account.country
     *
     * @param country the value for tb_wx_account.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_account.language
     *
     * @return the value of tb_wx_account.language
     *
     * @mbggenerated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wx_account.language
     *
     * @param language the value for tb_wx_account.language
     *
     * @mbggenerated
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }
}